name: Inject Secrets and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API URLs and Authorization Token
        env:
          API_FLUX_1_DEV: ${{ secrets.API_FLUX_1_DEV }}
          API_FLUX_1_3D: ${{ secrets.API_FLUX_1_3D }}
          API_FLUX_1_PANORAMA: ${{ secrets.API_FLUX_1_PANORAMA }}
          API_FLUX_1_ILLUSTRATION: ${{ secrets.API_FLUX_1_ILLUSTRATION }}
          API_FLUX_1_SCHNELL: ${{ secrets.API_FLUX_1_SCHNELL }}
          API_STABLE_DIFFUSION_3_5: ${{ secrets.API_STABLE_DIFFUSION_3_5 }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          sed -i 's|API_URL_FLUX_1_DEV|'"$API_FLUX_1_DEV"'|g' index.html
          sed -i 's|API_URL_FLUX_1_3D|'"$API_FLUX_1_3D"'|g' index.html
          sed -i 's|API_URL_FLUX_1_PANORAMA|'"$API_FLUX_1_PANORAMA"'|g' index.html
          sed -i 's|API_URL_FLUX_1_ILLUSTRATION|'"$API_FLUX_1_ILLUSTRATION"'|g' index.html
          sed -i 's|API_URL_FLUX_1_SCHNELL|'"$API_FLUX_1_SCHNELL"'|g' index.html
          sed -i 's|API_URL_STABLE_DIFFUSION_3_5|'"$API_STABLE_DIFFUSION_3_5"'|g' index.html
          sed -i 's|AUTH_TOKEN_PLACEHOLDER|'"$HUGGINGFACE_TOKEN"'|g' script.js

      - name: List files to verify upload
        run: |
          ls -al
          cat index.html
          cat script.js

      - name: Upload files for deployment
        uses: actions/upload-artifact@v3
        with:
          name: site  # نام artifact که باید در مرحله deploy نیز همین نام استفاده شود
          path: |
            index.html
            script.js
            assets/  # پوشه‌ها و فایل‌های دیگر

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List files to check artifact availability
        run: |
          ls -al

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          name: site  # نام صحیح که باید برای artifact استفاده شود
