name: Inject Secrets and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # شاخه‌ای که می‌خواهید Workflow روی آن اجرا شود.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Inject Secrets into HTML and JavaScript files
      - name: Inject API URLs and Authorization Token
        env:
          API_FLUX_1_DEV: ${{ secrets.API_FLUX_1_DEV }}
          API_FLUX_1_3D: ${{ secrets.API_FLUX_1_3D }}
          API_FLUX_1_PANORAMA: ${{ secrets.API_FLUX_1_PANORAMA }}
          API_FLUX_1_ILLUSTRATION: ${{ secrets.API_FLUX_1_ILLUSTRATION }}
          API_FLUX_1_SCHNELL: ${{ secrets.API_FLUX_1_SCHNELL }}
          API_STABLE_DIFFUSION_3_5: ${{ secrets.API_STABLE_DIFFUSION_3_5 }}
          HUG_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          # جایگزینی API URLs در فایل HTML
          sed -i 's|API_URL_FLUX_1_DEV|'"$API_FLUX_1_DEV"'|g' index.html
          sed -i 's|API_URL_FLUX_1_3D|'"$API_FLUX_1_3D"'|g' index.html
          sed -i 's|API_URL_FLUX_1_PANORAMA|'"$API_FLUX_1_PANORAMA"'|g' index.html
          sed -i 's|API_URL_FLUX_1_ILLUSTRATION|'"$API_FLUX_1_ILLUSTRATION"'|g' index.html
          sed -i 's|API_URL_FLUX_1_SCHNELL|'"$API_FLUX_1_SCHNELL"'|g' index.html
          sed -i 's|API_URL_STABLE_DIFFUSION_3_5|'"$API_STABLE_DIFFUSION_3_5"'|g' index.html

          # جایگزینی Authorization Token در فایل script.js
          sed -i 's|AUTH_TOKEN_PLACEHOLDER|'"$HUG_TOKEN"'|g' script.js

      # 3. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
